name: Joyned Git LFS Linter

on:
  workflow_call:

jobs:
  lint-lfs:
    name: Lint LFS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint LFS
        run: git lfs fsck --pointers
